version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD='1'
      - MYSQL_ROOT_HOST='172.20.0.1'
    command: mysqld --sql_mode=""
    ports:
      - '3306:3306'
    volumes:
      - ../mysql:/var/lib/mysql
